from .request_keyboards import create_kp_operation_type
from .request_keyboards import create_kb_choose_card
from .request_keyboards import create_kb_choose_currency
from .request_keyboards import create_kb_send_request
from .request_keyboards import create_kb_plus_minus
from .request_keyboards import create_kb_smart_choose_curr
from .request_keyboards import create_kb_send_request_for_change
from .request_keyboards import create_kb_send_request_atm