from .keyboard_current_requests import create_kb_current_requests
from .keyboard_current_requests import cb_current_requests

from .keyboard_chosen_request import create_kb_chosen_request
from .keyboard_chosen_request import cb_chosen_requests

from .keyboards_sum_ready import create_kb_what_sum
from .keyboards_sum_ready import cb_what_sum

from .keyboards_sum_ready import create_kb_choose_currency_processing
from .keyboards_sum_ready import cb_choose_currency

from .confirm_keyboard import create_kb_confirm_close
from .confirm_keyboard import cb_confirm_close

from .keyboards_sum_ready import create_kb_what_sum_correct
from .keyboards_sum_ready import cb_what_sum_correct

from .keyboards_sum_ready import create_kb_sum_correct_chunk
from .keyboards_sum_ready import cb_sum_correct_chunk

from .blue_keyboard import create_kb_what_blue
from .blue_keyboard import cb_what_bluе

from .blue_keyboard import create_kb_confirm_blue
from .blue_keyboard import cb_confirm_blue

from .keyboards_correct_to_ready import create_kb_corrected_sum
from .keyboards_correct_to_ready import cb_corrected_sum

from .confirm_reserve_to_ready import create_kb_confirm_reserve
from .confirm_reserve_to_ready import cb_confirm_reserve

from .message_keyboards import create_kb_message_keyboard
from .message_keyboards import cb_message_keyboard

from .keyboards_close_request import create_kb_confirm_close_request
from .keyboards_close_request import cb_confirm_close_request

from .keyboards_close_request import create_kb_which_sum_close
from .keyboards_close_request import cb_which_sum_close

from .change_request_keyboards import create_kb_change_request
from .change_request_keyboards import cb_change_request

from .change_request_keyboards import create_kb_change_date