# from .default import main_menu
from .default import create_kb_coustom_main_menu

from .inline import create_kp_operation_type
from .inline import create_kb_choose_currency
from .inline import create_kb_choose_card
from .inline import create_kb_send_request
from .inline import create_kb_plus_minus
from .inline import create_kb_smart_choose_curr
from .inline import create_kb_send_request_for_change
from .inline import create_kb_send_request_atm
from .inline import create_kb_current_requests
from .inline import create_kb_chosen_request
from .inline import create_kb_what_sum
from .inline import create_kb_choose_currency_processing
from .inline import create_kb_choose_date
from .inline import create_kb_confirm_close
from .inline import create_kb_what_sum_correct
from .inline import create_kb_what_blue
from .inline import create_kb_confirm_blue
from .inline import create_kb_corrected_sum
from .inline import create_kb_all_permits
from .inline import create_kb_set_status_permit
from .inline import create_kb_who_waste
from .inline import create_kb_yes_no_note
from .inline import create_kb_for_what_waste
from .inline import create_kb_confirm_reserve
from .inline import create_kb_sum_correct_chunk
from .inline import create_kb_message_keyboard
from .inline import create_kb_confirm_close_request
from .inline import create_kb_which_sum_close
from .inline import create_kb_change_request
from .inline import create_kb_change_date
from .inline import create_kb_new_request_type
from .inline import create_kb_another_currecy_add
from .inline import create_kb_choose_give_recive_change
from .inline import create_kb_confirm_cancel_request
from .inline import create_kb_confirm_single_permit

from .inline import cb_current_requests
from .inline import cb_chosen_requests
from .inline import cb_what_sum
from .inline import cb_choose_currency
from .inline import cb_confirm_close
from .inline import cb_what_sum_correct
from .inline import cb_what_bluе
from .inline import cb_confirm_blue
from .inline import cb_corrected_sum
from .inline import cb_all_permits
from .inline import cb_set_status_prmt
from .inline import cb_who_waste
from .inline import cb_yes_no_note
from .inline import cb_for_what_waste
from .inline import cb_confirm_reserve
from .inline import cb_sum_correct_chunk
from .inline import cb_message_keyboard
from .inline import cb_confirm_close_request
from .inline import cb_which_sum_close
from .inline import cb_change_request
from .inline import cb_anoter_currency_add